### ISSUE TITLE
Collector

### ISSUE THREAD

**Issue by Miraculous14** [cloudforet-io/docs#112]
![图片](https://user-images.githubusercontent.com/94815722/234165965-26501795-ecaf-489f-995f-3197196c2687.png)
Who can tell me the reason for this?

**Comment by choonho** [comment]
Sorry for late response.
I just noticed your issue.

The reason for collector plugin failure is related with wrong installation.

In the Cloudforet, "Create Collector" means deployment of new collector POD in a kubernetes.

The possible failure is

* Fail to deploy collector POD, lack of permission.
* Fail to pull collector Docker Image, lack of timeout (ex. spaceone/plugin-aws-cloud-service-inven-collector)


Please check the log of supervisor POD in root-supervisor namespace.

~~~
[ec2-user@choonho-dev ~]$ kubectl config set-context $(kubectl config current-context) --namespace root-supervisor
Context "minikube" modified.
[ec2-user@choonho-dev ~]$ k get pod
NAME                                   READY   STATUS    RESTARTS   AGE
supervisor-scheduler-f96658745-rvgm7   3/3     Running   0          8d
[ec2-user@choonho-dev ~]$ k logs -f supervisor-scheduler-f96658745-rvgm7
~~~

# Question

* What is your installation guide?
* https://cloudforet.io/docs/setup_operation/quick_install/
If you installed above guide, I also found the missing content of installation.

I will update document.

**Comment by choonho** [comment]
I will update trouble shooting notes of version 1.11.0

[](https://github.com/orgs/cloudforet-io/discussions/121)
