### ISSUE TITLE
Wrong example content

### ISSUE THREAD

**Issue by choonho** [cloudforet-io/docs#173]
In the "On Premise" installation guide, there is wrong yaml file content.

https://cloudforet.io/docs/setup_operation/installation/on_premise/

![image](https://github.com/cloudforet-io/docs/assets/3993088/c72d71f1-351a-4982-86da-56eda87ce7ac)

The correct content is 
https://github.com/cloudforet-io/charts/blob/master/examples/initializer.yaml

**Comment by arup1221** [comment]
I got second one (https://github.com/cloudforet-io/charts/blob/master/examples/initializer.yaml)  only

**Comment by achiverram28** [comment]
> I got second one (https://github.com/cloudforet-io/charts/blob/master/examples/initializer.yaml) only

In the docs , the indentation is not proper

@choonho I have corrected the helm version here too

**Comment by arup1221** [comment]
Ohh! actually I  can't check properly, Thanks!
