### ISSUE TITLE
Getting Started in Windows Environment

### ISSUE THREAD

**Issue by choonho** [cloudforet-io/docs#184]
Installation of Cloudforet at Windows + Docker Desktop + WSL2 is possible.

If anyone has a blog about this, I will append link in **Getting Started**.

**Comment by Ayush-Sharma410** [comment]
@choonho please check my blog for installation of cloudforet in windows.
Here is the link --> (https://medium.com/@ayushsharma2267410/installation-of-cloudforet-in-windows-8c4a10c9a65f)
Please review and tell if any changes needed.
Thank you

**Comment by choonho** [comment]
> @choonho please check my blog for installation of cloudforet in windows. Here is the link --> (https://medium.com/@ayushsharma2267410/installation-of-cloudforet-in-windows-8c4a10c9a65f) Please review and tell if any changes needed. Thank you

@Ayush-Sharma410 Can you describe more about Windows WSL2 and Docker installation also?
Most difficulties are related with WSL2 and port-forwarding in Windows.

**Comment by Ayush-Sharma410** [comment]
@choonho can i include the links for other blogs in my blog for docker desktop and wsl installation?
The articles that i followed myself for this are : 
Docker--> (https://www.simplilearn.com/tutorials/docker-tutorial/install-docker-on-windows)
Wsl--> (https://learn.microsoft.com/en-us/windows/wsl/install)

**Comment by choonho** [comment]
> @choonho can i include the links for other blogs in my blog for docker desktop and wsl installation? The articles that i followed myself for this are : Docker--> (https://www.simplilearn.com/tutorials/docker-tutorial/install-docker-on-windows) Wsl--> (https://learn.microsoft.com/en-us/windows/wsl/install)

@Ayush-Sharma410 Good information, can you append these links in your blog content?

**Comment by Ayush-Sharma410** [comment]
@choonho I have appended the links. Please review for any further changes.
https://medium.com/@ayushsharma2267410/installation-of-cloudforet-in-windows-8c4a10c9a65f

**Comment by Ayush-Sharma410** [comment]
@choonho Please review for any changes.

**Comment by choonho** [comment]
> @choonho Please review for any changes.

@Ayush-Sharma410 Please make PR for Windows use-case.

In the ***Link(ex. Blog)***, add your blog link.

https://cloudforet.io/docs/setup_operation/quick_install/

**Comment by Ayush-Sharma410** [comment]
@choonho Please review the PR and tell if any changes required.
