### ISSUE TITLE
Wrong URL link

### ISSUE THREAD

**Issue by choonho** [cloudforet-io/docs#194]
Cloudforet minimal installation has wrong value file content.

![image](https://github.com/cloudforet-io/docs/assets/3993088/dde04f45-9ce2-4a39-bcd3-83b44ca1c52e)

The link is ***https://cloudforet.io/docs/setup_operation/quick_install/examples/initializer.yaml***

It should be ***https://raw.githubusercontent.com/cloudforet-io/charts/master/examples/initializer.yaml***

**Comment by arup1221** [comment]
#197 I made a pull request on it. Please check.

**Comment by choonho** [comment]
Delete yaml content in docs, and link to charts one.
