### ISSUE TITLE
Wrong URL link

### ISSUE THREAD

**Issue by choonho** [cloudforet-io/docs#195]
![image](https://github.com/cloudforet-io/docs/assets/3993088/d2ac635e-b09d-43a6-b7b4-085d847dfa80)

Change wrong link to
https://raw.githubusercontent.com/cloudforet-io/charts/master/examples/rbac.yaml

**Comment by arup1221** [comment]
#196    I made a pull request on it. Please check.

**Comment by choonho** [comment]
Delete yaml content in docs, and link to charts one.

**Comment by arup1221** [comment]
> Delete yaml content in docs, and link to charts one.

Sorry, I can't understand what to do

**Comment by choonho** [comment]
@arup1221 Your commit was updating the contents of ***https://github.com/cloudforet-io/docs/blob/master/content/en/docs/setup_operation/quick_install/examples/initializer.yaml***

The original content is at ***https://github.com/cloudforet-io/charts/blob/master/examples/initializer.yaml***

Instead of updating the contents itself, change the link target to ***https://github.com/cloudforet-io/charts/blob/master/examples/initializer.yaml***

**Comment by arup1221** [comment]
ok I understand, Thank You
